language: python
sudo: required
services:
  - docker
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
after_script:
  - docker build -t madscientist/kiwi-pycon-2017 .
  - docker push madscientist/kiwi-pycon-2017
