version: '2'
services:
  nginx:
    image: nginx:1.13
    restart: always
    ports:
       - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    networks:
      - frontend
    depends_on:
      - api
  db:
    restart: always
    image: postgres:10
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  api:
    env_file:
      - .env 
    restart: always
    environment:
      - DOCKER=True
    build: .
    image: my-api
    command: bash docker_entrypoint.sh
    volumes:
      - .:/src
    depends_on:
      - db
    networks:
      - frontend
      - backend
  django_q:
    restart: always
    environment:
      - DOCKER=True
    build: .
    image: my-api
    command: python manage.py qcluster
    networks:
      - backend
    volumes:
      - .:/src
    depends_on:
      - db
  redis:
    restart: always
    image: redis:3
    networks:
      - backend
networks:
  backend:
  frontend:
